name: Build and Deploy Java Spring Boot Application

on:
  push:
    branches:
      - main  # Trigger the workflow on push to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 22.04 (or 24.04 soon)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Ensure code is checked out before build

    - name: Set up JDK
      uses: actions/setup-java@v3  # Set up the Java environment
      with:
        java-version: '17'  # Ensure you’re using the correct Java version for your project
        distribution: 'temurin'  # Temurin is the OpenJDK distribution

    # Change directory to the folder containing your 'pom.xml' (if needed)
    - name: Navigate to project directory
      run: cd Examensarbete_JAVA23_TAXI  # Change this path if necessary

    - name: Build with Maven (with debug mode)
      run: mvn clean package -X --file Examensarbete_JAVA23_TAXI/pom.xml  # Specify the path to the pom.xml file

    # Run the application (after build)
    - name: Run Application
      run: java -jar Examensarbete_JAVA23_TAXI/target/*.jar  # Ensure the path matches your project output directory
